POST http://localhost:3000/todos/
Content-Type: application/json 

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "AVERAGE",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

### 

GET http://localhost:3000/todos/
###

GET http://localhost:3000/todos/4
###


PUT http://localhost:3000/todos/4/
Content-Type: application/json

{
      "status" : "AVERAGE"
}

###

DELETE http://localhost:3000/todos/3/
###